name: Daily Ronnie Radke News Trigger

on:
  schedule:
    - cron: "00 16 * * *"  # 12:00 EST
  workflow_dispatch:
    inputs:
      random:
        description: "Send a random news item?"
        required: false
        default: "false"

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run news bot
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          BRAVE_TOKEN: ${{ secrets.BRAVE_TOKEN }}
          RANDOM: ${{ github.event.inputs.random || 'false' }}
        run: python send_news.py
