name: Daily Ronnie Radke News Trigger

on:
  schedule:
    - cron: "00 16 * * *"  # 12:00 EST
  workflow_dispatch:
    inputs:
      endpoint:
        description: "Endpoint to ping (e.g. /trigger, /random)"
        required: false
        default: "/trigger"

jobs:
  ping_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger endpoint
        run: |
          curl -X GET "${{ secrets.BASE_URL }}${{ github.event.inputs.endpoint || '/trigger' }}"