name: Daily Ronnie Radke News Trigger

on:
  schedule:
    - cron: "00 16 * * *"  # 12:00 EST
  workflow_dispatch:
    inputs:
      endpoint:
        description: "Endpoint to ping (e.g. /trigger, /random)"
        required: false
        default: "/trigger"

jobs:
  ping_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Determine endpoint
        id: set-endpoint
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "endpoint=${{ secrets.SCHEDULE_ENDPOINT }}" >> "$GITHUB_OUTPUT"
          else
            echo "endpoint=${{ github.event.inputs.endpoint || '/trigger' }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Ping endpoint
        run: |
          curl -X GET "${{ secrets.BASE_URL }}${{ steps.set-endpoint.outputs.endpoint }}"
